# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slg_vae',
                'doc_host': 'https://slegroux.github.io',
                'git_url': 'https://github.com/slegroux/slg_vae',
                'lib_path': 'slg_vae'},
  'syms': { 'slg_vae.core': {'slg_vae.core.foo': ('core.html#foo', 'slg_vae/core.py')},
            'slg_vae.vae': { 'slg_vae.vae.foo': ('vae.html#foo', 'slg_vae/vae.py'),
                             'slg_vae.vae.test': ('vae.html#test', 'slg_vae/vae.py')}}}
