# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_vae.ipynb.

# %% auto 0
__all__ = ['foo', 'test']

# %% ../nbs/00_vae.ipynb 3
def foo(): pass

# %% ../nbs/00_vae.ipynb 4
def test(a:float, b:float):
    """_summary_

    Args:
        a (float): _description_
        b (float): _description_

    Returns:
        _type_: _description_
    """
    return a+b
